#!/usr/bin/env node
/**
 * Builds the district_thanas master (see migrations/0012_add_district_thanas.sql) from the
 * shop data. One row per distinct (district, circle/sector, thana) with a normalised
 * thana_key and the shop count behind it.
 *
 * Source: the local MariaDB analysis clone of prod D1 (docs/local-analysis-db.md), which
 * `.env.local-analysis-db` points at. Its phase1_raw_collection row count was checked equal
 * to remote D1's before this was run, so there is no staleness gap for this derivation.
 *
 * Emits a .sql file of INSERT batches; it does not touch any database itself. Apply with:
 *   wrangler d1 execute up-excise-spatial-revenue-optimizer-prod --local  --file=<out>
 *   wrangler d1 execute up-excise-spatial-revenue-optimizer-prod --remote --file=<out>
 *
 * Usage: pnpm tsx scripts/build-district-thanas.ts [outfile]
 */

import { execFileSync } from 'node:child_process';
import { readFileSync, writeFileSync } from 'node:fs';
import { join, dirname } from 'node:path';
import { fileURLToPath } from 'node:url';
import { tmpdir } from 'node:os';

const __dirname = dirname(fileURLToPath(import.meta.url));

// normalizeThanaName from apps/web/src/lib/thana-name.ts — kept in sync by hand (this script
// is outside the Next build graph). Trimmed, internal whitespace collapsed, lowercased.
const normalizeThanaName = (s: string) => (s ?? '').trim().replace(/\s+/g, ' ').toLowerCase();
const esc = (s: string) => "'" + s.replace(/'/g, "''") + "'";

function loadEnv(): Record<string, string> {
  const raw = readFileSync(join(__dirname, '..', '.env.local-analysis-db'), 'utf-8');
  const env: Record<string, string> = {};
  for (const line of raw.split(/\r?\n/)) {
    const m = line.match(/^\s*([A-Z_]+)\s*=\s*(.*)\s*$/);
    if (m) env[m[1]!] = m[2]!.replace(/^["']|["']$/g, '');
  }
  return env;
}

const env = loadEnv();
const host = env.DB_HOST || '127.0.0.1';
const port = env.DB_PORT || '3306';
const user = env.DB_USERNAME!;
const pass = env.DB_PASSWORD!;
const db = env.DB_DATABASE!;

const sql = `
  SELECT district_name, circle_sector_name, thana_name, COUNT(*) AS c
  FROM phase1_raw_collection
  WHERE thana_name IS NOT NULL AND TRIM(thana_name) <> ''
  GROUP BY district_name, circle_sector_name, thana_name
  ORDER BY district_name, circle_sector_name, thana_name
`;

const tsv = execFileSync(
  'mysql',
  ['-h', host, '-P', port, `-u${user}`, `-p${pass}`, db, '--batch', '--raw', '-N', '-e', sql],
  { encoding: 'utf-8', maxBuffer: 64 * 1024 * 1024 },
);

const rows = tsv.split('\n').filter(Boolean).map((line) => {
  const [district, unit, thana, count] = line.split('\t');
  return { district: district!, unit: unit!, thana: thana!, count: Number(count) || 0 };
});

if (rows.length === 0) {
  console.error('No rows returned — is the analysis DB populated?');
  process.exit(1);
}

const districts = new Set(rows.map((r) => r.district));
const values = rows.map(
  (r) => `(${esc(r.district)}, ${esc(r.unit)}, ${esc(r.thana)}, ${esc(normalizeThanaName(r.thana))}, ${r.count})`,
);

const CHUNK = 200;
const out: string[] = [
  '-- district_thanas master, generated by scripts/build-district-thanas.ts',
  `-- ${rows.length} (district, circle/sector, thana) rows across ${districts.size} districts`,
  'DELETE FROM district_thanas;',
];
for (let i = 0; i < values.length; i += CHUNK) {
  out.push(
    'INSERT INTO district_thanas (district_name, circle_sector_name, thana_name, thana_key, shop_count) VALUES\n' +
    values.slice(i, i + CHUNK).join(',\n') + ';',
  );
}

const outfile = process.argv[2] || join(tmpdir(), `district-thanas-${Date.now()}.sql`);
writeFileSync(outfile, out.join('\n') + '\n', 'utf-8');

const distinctThanaKeys = new Set(rows.map((r) => `${r.district}||${normalizeThanaName(r.thana)}`));
console.log(`Wrote ${outfile}`);
console.log(`  ${rows.length} tuples, ${distinctThanaKeys.size} distinct (district, thana_key), ${districts.size} districts`);
